import { Course } from "@/types/course";

const coursesData: Course[] = [
  {
    id: 1,
    title: "Master Diploma in Fashion Designing",
    duration: "2 Years",
    level: "Advanced",
    description:
      "Comprehensive 2-year program to master all aspects of fashion design from concept to production",
    image: "/images/courses/1.webp",
    highlights: [
      "Industry-standard curriculum",
      "Live project experience",
      "International faculty",
      "100% job placement",
    ],
    learningOutcomes: [
      "Master advanced pattern making and garment construction",
      "Develop unique design aesthetic and design philosophy",
      "Create professional fashion collections",
      "Learn digital design tools and 3D visualization",
      "Understand fashion business and entrepreneurship",
    ],
    curriculum: [
      "Fashion Design Fundamentals",
      "Advanced Pattern Making",
      "Garment Construction",
      "Fashion Illustration",
      "Fabric Science",
      "Draping Techniques",
      "CAD Design (CLO 3D, Lectra)",
      "Fashion Marketing",
      "Trend Forecasting",
      "Portfolio Development",
      "Live Industry Projects",
    ],
    studentFeedback: [
      {
        id: 1,
        studentName: "Priya Sharma",
        studentImage: "/images/testimonials/auth-01.png",
        date: "2024",
        rating: 5,
        feedback:
          "This course completely transformed my career. The industry exposure and mentorship were invaluable. Now working at ASOS!",
        designation: "ASOS Fashion Designer",
      },
      {
        id: 2,
        studentName: "Rahul Singh",
        studentImage: "/images/testimonials/auth-02.png",
        date: "2024",
        rating: 5,
        feedback:
          "The practical training and real-world projects are exceptional. I feel confident starting my own brand now.",
        designation: "Fashion Entrepreneur",
      },
      {
        id: 3,
        studentName: "Sneha Roy",
        studentImage: "/images/testimonials/auth-03.png",
        date: "2024",
        rating: 5,
        feedback:
          "Faculty members are industry veterans who truly care about student success. Highly recommended!",
        designation: "Vogue India Designer",
      },
    ],
    achievements: [
      {
        id: 1,
        title: "Professional Certification",
        description: "Recognized industry certification",
        icon: "🏆",
      },
      {
        id: 2,
        title: "Portfolio Ready",
        description: "Create a professional portfolio",
        icon: "📁",
      },
      {
        id: 3,
        title: "Career Placement",
        description: "100% placement assistance",
        icon: "💼",
      },
    ],
  },
  {
    id: 2,
    title: "Advanced Diploma in Fashion Design",
    duration: "1 Year",
    level: "Intermediate",
    description:
      "Intensive 1-year program for those with basic fashion knowledge to enhance their design skills",
    image: "/images/courses/2.webp",
    highlights: [
      "Specialized modules",
      "Portfolio building",
      "Industry internships",
      "Expert guidance",
    ],
    learningOutcomes: [
      "Develop advanced design techniques and style development",
      "Master computer-aided design tools",
      "Create a professional design portfolio",
      "Learn about fashion business essentials",
      "Build network with industry professionals",
    ],
    curriculum: [
      "Fashion Design Theory",
      "Costume Design",
      "Textile Design",
      "Digital Fashion Design",
      "Fashion Photography",
      "Styling & Personal Branding",
      "Fashion Business Basics",
      "Portfolio Development",
      "Industry Internship",
    ],
    studentFeedback: [
      {
        id: 1,
        studentName: "Ananya Gupta",
        studentImage: "/images/testimonials/auth-04.png",
        date: "2024",
        rating: 5,
        feedback:
          "Great program for working professionals. Flexible schedule and quality education. Worth every penny!",
        designation: "Flipkart Fashion Manager",
      },
    ],
    achievements: [
      {
        id: 1,
        title: "Advanced Skills",
        description: "Master specialized techniques",
        icon: "⭐",
      },
      {
        id: 2,
        title: "Industry Network",
        description: "Connect with fashion leaders",
        icon: "🤝",
      },
    ],
  },
  {
    id: 3,
    title: "Fashion Design Diploma",
    duration: "1 Year",
    level: "Beginner",
    description:
      "Foundation 1-year program perfect for beginners who want to start a fashion design career",
    image: "/images/courses/3.jpg",
    highlights: [
      "Comprehensive basics",
      "Hands-on training",
      "Creative projects",
      "Certificate upon completion",
    ],
    learningOutcomes: [
      "Understand fashion design principles and history",
      "Learn pattern making and construction basics",
      "Develop illustration skills",
      "Understand fabric properties and selection",
      "Create basic fashion collections",
    ],
    curriculum: [
      "Fashion Design Basics",
      "Fashion History & Trends",
      "Sketching & Illustration",
      "Pattern Making Fundamentals",
      "Garment Construction",
      "Fabric Knowledge",
      "Color & Design Theory",
      "Fashion Projects",
    ],
    studentFeedback: [
      {
        id: 1,
        studentName: "Vikram Patel",
        studentImage: "/images/testimonials/auth-05.png",
        date: "2024",
        rating: 5,
        feedback:
          "Perfect starting point for anyone interested in fashion. Teachers are supportive and curriculum is well-structured.",
        designation: "Raymond Menswear Designer",
      },
    ],
    achievements: [
      {
        id: 1,
        title: "Foundation Certificate",
        description: "Official completion certificate",
        icon: "📜",
      },
      {
        id: 2,
        title: "Portfolio Start",
        description: "Build your first portfolio",
        icon: "🎨",
      },
    ],
  },
  {
    id: 4,
    title: "Certificate in Garment Making",
    duration: "6 Months",
    level: "Beginner",
    description:
      "Quick 6-month certification course focused on practical garment construction and tailoring",
    image: "/images/courses/4.jpg",
    highlights: [
      "Practical skills focus",
      "Quick certification",
      "Industry-ready training",
      "Affordable pricing",
    ],
    learningOutcomes: [
      "Master basic garment construction techniques",
      "Learn professional tailoring methods",
      "Understand different garment types",
      "Develop production efficiency skills",
      "Ready for entry-level positions",
    ],
    curriculum: [
      "Fabric Selection & Care",
      "Basic Pattern Making",
      "Hand Stitching Techniques",
      "Machine Stitching",
      "Garment Construction Methods",
      "Quality Control",
      "Production Planning",
    ],
    studentFeedback: [
      {
        id: 1,
        studentName: "Arjun Kapoor",
        studentImage: "/images/testimonials/auth-06.png",
        date: "2024",
        rating: 5,
        feedback:
          "Excellent hands-on training. Got a job at a garment factory just 2 months after completing the course!",
        designation: "Lifestyle Brand Tailor",
      },
    ],
    achievements: [
      {
        id: 1,
        title: "Professional Certificate",
        description: "Garment making certification",
        icon: "✂️",
      },
    ],
  },
  {
    id: 5,
    title: "International Diploma In Montessori TTC",
    duration: "Variable",
    level: "Professional",
    description:
      "Internationally recognized Montessori Teacher Training Course for aspiring early childhood educators",
    image: "/images/courses/5.jpg",
    highlights: [
      "International certification",
      "Early childhood education focus",
      "Montessori methodology",
      "Global recognition",
    ],
    learningOutcomes: [
      "Master Montessori teaching philosophy and methods",
      "Learn child development and psychology",
      "Develop classroom management skills",
      "Create Montessori learning materials",
      "Understand international teaching standards",
    ],
    curriculum: [
      "Montessori Philosophy",
      "Child Psychology",
      "Practical Life Activities",
      "Sensorial Education",
      "Language Development",
      "Mathematics Fundamentals",
      "Cultural Studies",
      "Classroom Management",
      "Parent-Teacher Collaboration",
      "Teaching Practice",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "International Certification",
        description: "Globally recognized credential",
        icon: "🌍",
      },
      {
        id: 2,
        title: "Teaching Excellence",
        description: "Master Montessori methods",
        icon: "👩‍🏫",
      },
    ],
  },
  {
    id: 6,
    title: "Diploma in Montessori TTC",
    duration: "Variable",
    level: "Professional",
    description:
      "Comprehensive Montessori Teacher Training Course preparing educators for early childhood education",
    image: "/images/courses/6.webp",
    highlights: [
      "Professional certification",
      "Hands-on training",
      "Child-centered approach",
      "Career opportunities",
    ],
    learningOutcomes: [
      "Implement Montessori teaching techniques",
      "Understand child development stages",
      "Create engaging learning environments",
      "Develop observation and assessment skills",
      "Build effective parent communication",
    ],
    curriculum: [
      "Introduction to Montessori Method",
      "Child Development",
      "Practical Life Skills",
      "Sensory Development",
      "Language Arts",
      "Math Concepts",
      "Science & Culture",
      "Art & Music",
      "Teaching Practicum",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Professional Diploma",
        description: "Montessori teaching certification",
        icon: "📚",
      },
      {
        id: 2,
        title: "Career Ready",
        description: "Prepared for teaching positions",
        icon: "🎓",
      },
    ],
  },
  {
    id: 7,
    title: "Advanced Diploma in Beauty & Wellness",
    duration: "1 Year",
    level: "Advanced",
    description:
      "Comprehensive 1-year program covering advanced beauty therapy, wellness, and spa management",
    image: "/images/courses/8.jpeg",
    highlights: [
      "Advanced techniques",
      "Spa management training",
      "Industry certification",
      "Business skills",
    ],
    learningOutcomes: [
      "Master advanced beauty and wellness techniques",
      "Learn spa and salon management",
      "Understand business operations in beauty industry",
      "Develop client consultation and care skills",
      "Gain expertise in various beauty treatments",
    ],
    curriculum: [
      "Advanced Skincare Treatments",
      "Hair Styling & Treatments",
      "Makeup Artistry",
      "Nail Technology",
      "Spa Therapies",
      "Aromatherapy",
      "Salon Management",
      "Customer Service Excellence",
      "Product Knowledge",
      "Business Development",
      "Health & Safety",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Advanced Certification",
        description: "Professional beauty & wellness credential",
        icon: "💅",
      },
      {
        id: 2,
        title: "Business Ready",
        description: "Start your own salon or spa",
        icon: "💼",
      },
    ],
  },
  {
    id: 8,
    title: "Certificate in Beauty & Wellness",
    duration: "6 Months",
    level: "Beginner",
    description:
      "Quick 6-month certification introducing essential beauty and wellness techniques",
    image: "/images/courses/9.jpg",
    highlights: [
      "Foundation training",
      "Quick certification",
      "Hands-on practice",
      "Industry basics",
    ],
    learningOutcomes: [
      "Learn basic beauty therapy techniques",
      "Understand skincare fundamentals",
      "Master basic makeup application",
      "Develop professional client service skills",
      "Get entry-level job readiness",
    ],
    curriculum: [
      "Skincare Basics",
      "Hair Care Fundamentals",
      "Basic Makeup Techniques",
      "Nail Care & Art",
      "Facial Treatments",
      "Waxing & Threading",
      "Hygiene & Sanitation",
      "Customer Relations",
      "Product Knowledge",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Foundation Certificate",
        description: "Beauty & wellness basics",
        icon: "✨",
      },
      {
        id: 2,
        title: "Career Start",
        description: "Entry to beauty industry",
        icon: "🎯",
      },
    ],
  },
  {
    id: 9,
    title: "Diploma In Medical Laboratory Technology (DMLT)",
    duration: "2 Years",
    level: "Advanced",
    description:
      "Comprehensive 2-year program training students in medical laboratory techniques and diagnostics",
    image: "/images/courses/10.jpg",
    highlights: [
      "Medical laboratory expertise",
      "Clinical training",
      "Healthcare career path",
      "Government recognition",
    ],
    learningOutcomes: [
      "Master laboratory diagnostic techniques",
      "Learn pathology and microbiology procedures",
      "Understand medical equipment operation",
      "Develop quality control and safety protocols",
      "Prepare for healthcare laboratory positions",
    ],
    curriculum: [
      "Human Anatomy & Physiology",
      "Clinical Pathology",
      "Clinical Biochemistry",
      "Microbiology",
      "Hematology",
      "Immunology & Serology",
      "Histopathology & Cytology",
      "Laboratory Management",
      "Quality Assurance",
      "Medical Ethics",
      "Clinical Training",
      "Research Methods",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Medical Diploma",
        description: "Professional DMLT certification",
        icon: "🔬",
      },
      {
        id: 2,
        title: "Healthcare Career",
        description: "Hospital & diagnostic lab opportunities",
        icon: "🏥",
      },
      {
        id: 3,
        title: "Government Recognition",
        description: "Recognized medical qualification",
        icon: "✅",
      },
    ],
  },
  {
    id: 10,
    title: "Medical Laboratory Technology (MLT)",
    duration: "1 Year",
    level: "Intermediate",
    description:
      "Intensive 1-year program focusing on essential medical laboratory technology skills",
    image: "/images/courses/11.webp",
    highlights: [
      "Focused curriculum",
      "Practical training",
      "Quick qualification",
      "Laboratory skills",
    ],
    learningOutcomes: [
      "Perform basic laboratory tests and procedures",
      "Understand medical terminology and protocols",
      "Operate laboratory equipment safely",
      "Maintain laboratory records and documentation",
      "Work in diagnostic and pathology laboratories",
    ],
    curriculum: [
      "Basic Anatomy & Physiology",
      "Clinical Pathology Basics",
      "Blood Banking",
      "Basic Biochemistry",
      "Microbiology Fundamentals",
      "Hematology Basics",
      "Laboratory Techniques",
      "Safety & Quality Control",
      "Medical Equipment Handling",
      "Laboratory Practice",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Professional Certificate",
        description: "MLT qualification",
        icon: "🧪",
      },
      {
        id: 2,
        title: "Lab Technician Ready",
        description: "Prepared for medical lab positions",
        icon: "💼",
      },
    ],
  },
  {
    id: 11,
    title: "Diploma in Hospital Administration",
    duration: "1 Year",
    level: "Professional",
    description:
      "Specialized 1-year program preparing students for administrative roles in healthcare facilities",
    image: "/images/courses/12.jpg",
    highlights: [
      "Healthcare management focus",
      "Administrative expertise",
      "Industry exposure",
      "Leadership development",
    ],
    learningOutcomes: [
      "Understand hospital operations and management",
      "Learn healthcare administration principles",
      "Master medical billing and coding basics",
      "Develop patient care coordination skills",
      "Understand healthcare laws and regulations",
    ],
    curriculum: [
      "Healthcare System Overview",
      "Hospital Organization & Management",
      "Medical Records Management",
      "Healthcare Finance & Budgeting",
      "Human Resource Management",
      "Medical Billing & Coding",
      "Quality Management in Healthcare",
      "Patient Care Services",
      "Healthcare Laws & Ethics",
      "Hospital Information Systems",
      "Communication Skills",
      "Internship",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Professional Diploma",
        description: "Hospital administration certification",
        icon: "🏥",
      },
      {
        id: 2,
        title: "Management Skills",
        description: "Healthcare leadership capabilities",
        icon: "📊",
      },
    ],
  },
  {
    id: 12,
    title: "Diploma in Office Administration",
    duration: "1 Year / 6 Months",
    level: "Beginner",
    description:
      "Flexible program available in 1-year or 6-month format covering essential office management skills",
    image: "/images/courses/13.jpg",
    highlights: [
      "Flexible duration options",
      "Practical office skills",
      "Computer proficiency",
      "Career versatility",
    ],
    learningOutcomes: [
      "Master office management and coordination",
      "Develop strong communication and organizational skills",
      "Learn computer applications and office software",
      "Understand business correspondence and documentation",
      "Build professional workplace etiquette",
    ],
    curriculum: [
      "Office Management Principles",
      "Business Communication",
      "Computer Applications (MS Office)",
      "Typing & Shorthand",
      "Records & File Management",
      "Business Correspondence",
      "Office Accounting Basics",
      "Customer Service",
      "Time Management",
      "Professional Ethics",
      "Practical Office Training",
    ],
    studentFeedback: [],
    achievements: [
      {
        id: 1,
        title: "Professional Certificate",
        description: "Office administration qualification",
        icon: "📋",
      },
      {
        id: 2,
        title: "Versatile Career",
        description: "Work in any industry",
        icon: "💼",
      },
    ],
  },
];

export default coursesData;